<?php
/**
 * Simple PDF Generator for Course Exports
 * Uses native PHP to generate PDF-compatible output
 */
class PDFGenerator {
    private $content = '';
    private $pageWidth = 595; // A4 width in points
    private $pageHeight = 842; // A4 height in points
    private $margin = 30;
    private $currentY = 50;
    
    public function __construct() {
        $this->content = '%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 ' . $this->pageWidth . ' ' . $this->pageHeight . ']
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length ';
    }
    
    public function addContent($html) {
        // Convert HTML to simple PDF content
        $text = strip_tags($html);
        $text = str_replace(["\r\n", "\r", "\n"], ' ', $text);
        
        // Simple PDF stream with basic text
        $this->content .= strlen($text) . '
>>
stream
BT
/F1 12 Tf
50 ' . $this->currentY . ' Td
(' . $this->escapePDFString($text) . ') Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000079 00000 n 
0000000173 00000 n 
0000000301 00000 n 
0000000400 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
500
%%EOF';
    }
    
    private function escapePDFString($string) {
        return str_replace(['\\', '(', ')', "\r", "\n"], ['\\\\', '\\(', '\\)', '\\r', '\\n'], $string);
    }
    
    public function output() {
        return $this->content;
    }
}

// Alternative: Use HTML to PDF conversion approach
function createSimplePDF($courses) {
    // Generate HTML with print-friendly styling
    $html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Course Report</title>
    <style>
        @page {
            size: A4;
            margin: 1cm;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.3;
            color: #000;
            margin: 0;
            padding: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .summary {
            margin-bottom: 15px;
            padding: 10px;
            background: #f5f5f5;
            border: 1px solid #ddd;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 6px 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #e0e0e0;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            font-size: 10px;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #333;
            padding: 5px 0;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0; font-size: 18px;">Course Management Report</h1>
        <p style="margin: 5px 0; font-size: 12px;">Generated on ' . date('Y-m-d H:i:s') . '</p>
    </div>
    
    <div class="summary">
        <strong>Summary:</strong><br>
        Total Courses: ' . count($courses) . '<br>
        Export Date: ' . date('Y-m-d H:i:s') . '<br>
        Generated by: IT HUB Admin System
    </div>
    
    <table>
        <thead>
            <tr>
                <th width="5%">ID</th>
                <th width="25%">Title</th>
                <th width="15%">Category</th>
                <th width="15%">Instructor</th>
                <th width="8%">Price</th>
                <th width="8%">Duration</th>
                <th width="10%">Difficulty</th>
                <th width="8%">Status</th>
                <th width="6%">Students</th>
                <th width="10%">Progress</th>
            </tr>
        </thead>
        <tbody>';

    foreach ($courses as $course) {
        $title = strlen($course['title']) > 40 ? substr($course['title'], 0, 37) . '...' : $course['title'];
        
        $html .= '
            <tr>
                <td>' . $course['id'] . '</td>
                <td>' . htmlspecialchars($title) . '</td>
                <td>' . htmlspecialchars($course['category_name'] ?? 'N/A') . '</td>
                <td>' . htmlspecialchars($course['instructor_name'] ?? 'N/A') . '</td>
                <td>Rs' . number_format($course['price'], 2) . '</td>
                <td>' . $course['duration_hours'] . 'h</td>
                <td>' . ucfirst($course['difficulty_level']) . '</td>
                <td>' . ucfirst($course['status']) . '</td>
                <td>' . ($course['enrollment_count'] ?? 0) . '</td>
                <td>' . round($course['avg_progress'] ?? 0) . '%</td>
            </tr>';
    }

    $html .= '
        </tbody>
    </table>
    
    <div class="footer">
        Page 1 of 1 | IT HUB Course Management System
    </div>
</body>
</html>';

    return $html;
}
?>
